version: '3.5'

services:
  pg:
    image: postgres:14.0-alpine
    volumes:
      - postgresql_last:/var/lib/postgresql/data
    env_file: ./.env.sample
    container_name: pg
    restart: on-failure

  redis:
    image: "redis:5-alpine"
    volumes:
      - redis_last:/data
    container_name: redis
    expose:
      - "6379"
    restart: always

  auth:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_NAME=AuthApp
      - FLASK_APP=app.py
    container_name: auth
    expose:
      - "8000"
    depends_on:
      - pg
      - redis

  nginx:
    container_name: nginx
    image: nginx:1.23.2
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf:ro
    ports:
      - 80:80
    depends_on:
      - auth

volumes:
  postgresql_last:
    name: postgresql_last
  redis_last:
    name: redis_last